### PR TITLE
Updated multipart-params to support progress listener.

### PR DESCRIPTION
**Pull request by akhudek**
The progress listener is useful for doing things like keeping a session alive during long uploads.

### CODE REVIEW

**Comment by weavejester** [comment]
Thanks for the patch. Can you ensure that the commit message follows the same rules as the rest of the repository? i.e. imperative tense and no period at the end of the summary line.

You should also rename `update-fn` to `progress-fn` for consistency, and you don't appear to have any code to parse the file items before they're passed to the progress function.

I'll also need to think about whether `:progress-fn` is the right name for this.

**Comment by JulianLeviston** [comment]
Imperative is a mood. Tense indicates time. Sorry for the overly pedantic comment, I just thought you might like to know for future reference :). BTW, totally love your work! :)

**Comment by weavejester** [comment]
Thanks for the correction, @JulianLeviston. TIL. :)

**Comment by akhudek** [comment]
Updated the commit messages and changed update-fn to progress-fn. What are you referring to with regards to parsing? The ProgressListener is only called with three integers.

**Comment by weavejester** [comment]
Apologies for the late response @akhudek, this PR managed to slip through the cracks of my inbox. So the `items` argument is more like `item-count` then?

**Comment by akhudek** [comment]
Yes, here are the field from the javadoc:

pBytesRead - The total number of bytes, which have been read so far.
pContentLength - The total number of bytes, which are being read. May be -1, if this number is unknown.
pItems - The number of the field, which is currently being read. (0 = no item so far, 1 = first item is being read, ...)

**Comment by weavejester** [comment]
Can you change the `items` argument to `item-count` instead?

**Comment by akhudek** [comment]
Done.

**Comment by weavejester** [comment]
Thanks. Could you update the docstring as well to reflect the change? Then please squash your commits.

**Comment by akhudek** [comment]
Done.

**Pull request merged**
