### PR TITLE
Add support for custom request map builder.

### PR DESCRIPTION
**Pull request by sachinpkale**
Adds :request-builder option to Jetty adapter.
Value of this option should be a function which takes instance of
HttpServletRequest as an argument and returns a request map.
If not provided ring.util.servlet/build-request-map will be used.

### CODE REVIEW

**Comment by weavejester** [comment]
Can you explain the use-case for this?

**Comment by sachinpkale** [comment]
We want to start rejecting requests which stayed in ThreadPool backed queue (mostly because server is under the load and there were no free threads to execute these requests). 
I checked whether it is possible in Jetty (http://dev.eclipse.org/mhonarc/lists/jetty-users/msg07858.html)
Now, decided to write a middleware which will reject request if the connection is created before, say 5 seconds (configurable value). For that, we need connection created timestamp in the request map.
I do not want to add it in default request map as it is very specific use case.
Also, not everyone would want all the attributes being populated by ring.util.servlet/build-request-map, so a custom request-map-builder can be provided.

**Comment by weavejester** [comment]
I think this is something that would be better handled inside the adapter, rather than by middleware. If Jetty doesn't already have a request queue timeout option, we could add one to the adapter.

**Comment by sachinpkale** [comment]
As per the mail thread (http://dev.eclipse.org/mhonarc/lists/jetty-users/msg07858.html), Servlet specification does not allow Jetty to interrupt the processing of a request.

**Comment by weavejester** [comment]
So you don't just want to reject requests that haven't been processed yet; you want to reject asynchronous requests that have been suspended?

**Comment by sachinpkale** [comment]
I just want to reject requests that are not processed within a given time limit.

**Comment by weavejester** [comment]
Does the time limit need to be precise? Could you, for instance, set the idle-timeout to 5 seconds, and then have some middleware that stops the handler from processing after 5 seconds. Worst case scenario is that your request will take 10 seconds to cancel at most.

**Comment by sachinpkale** [comment]
Yes, it should be precise (+ or - few ms). This step is to reduce load on servers by rejecting requests which are already timed out at client side. If the throughput is very high, server will get a lot of requests in 5 seconds.

**Comment by sachinpkale** [comment]
Also, in case of Jetty. idleTimeout parameter is being ignored as mentioned in the previously mentioned mail thread.

**Comment by weavejester** [comment]
I'm not sure I like the idea of adding an option to construct the request map to the adapter. To my mind it exposes too much of the internal functionality and sets a bad precedent for other adapters.

Adding a timestamp to the request map could be useful in general, but it might not be achievable with all adapters and web servers; some research would need to be done into it.

I think if you really need this functionality in the short term, you'd be best off forking the adapter and customising it to your own circumstances.

**Comment by sachinpkale** [comment]
Yeah, forking and using own version of modified adapter is the last option that we have.
But the custom builder will always build request map from the instance of HttpServletRequest (Same as ring.util.servlet/build-request-map). It would not have any other argument to build request-map from. Why should we restrict request-map to the fixed key set always even if requirements can be different? In my opinion, as far as attributes can be fetched from HttpServletRequest instance, they should be safe to use.
For example, HttpServletRequest has getTimeStamp() method which gives the timestamp of when the actual request execution started. This can also be useful.
My use-case is little different. `getTimeStamp() ` gives the timestamp when a request is picked from queue by a worker thread. I want to know the timestamp of when the HttpConnection is created. It is also present in HttpServletRequest.
In my case, I would use something like following (Java code):
`request.getAttribute("org.eclipse.jetty.server.HttpConnection").getCreatedTimeStamp()`
Actually, ^^ should be the actual request timestamp. I will follow-up with Jetty-devs to get it clarified.
If you are not comfortable with cutom-builder, can we at-leat add request-timestamp and connection-timestamp to the adapter?

**Comment by weavejester** [comment]
Adapters have a a specific contract: they turn a HTTP request into a Ring request map, pass it to the handler, then turn the resulting Ring response back into a HTTP response. That should be inviolate, but adding a request builder exposes that contract to alteration.

I'm slightly more amenable to something that *extends* the request map. That is, a function like:

```clojure
(fn [request-map servlet-request] request-map)
```

This has the same problems, but at least it hints that we should keep the request map intact.

Alternatively, the `HttpServletRequest` and `HttpServletResponse` objects could be added to `:servlet-request` and `:servlet-response` keys, respectively. This is already what happens when Ring is deployed as a servlet directly. I think this is the option that feels the least bad to me.

Also bare in mind that any changes that are adopted will take a while to make their way into a Ring release. Ring tends to have a slow release cycle, as we want to be careful about breaking things, or introducing new features that later prove to be ill thought out. Usually it's better to put anything experimental into a different library.

**Comment by sachinpkale** [comment]
I like the idea of adding `HttpServletRequest ` as a `:servlet-request` key. 
Should I go ahead with this change?  Will create another pull request with this change.
Anyway, will go with forking and using these changes for now. Will switch to Ring again once next version is released.

**Pull request closed without merging**
