### PR TITLE
Add config option to not to send Server header

### PR DESCRIPTION
**Pull request by whysoserious**
Title says all. 

_I need this feature in my commercial project. It was marked as a potential security hole in our security audit report._

### CODE REVIEW

**Comment by weavejester** [comment]
If you need this feature soon, you may want to use the `:configurator` option in your project, which allows you to configure the Jetty server directly.

Regarding the patch itself, there are some minor style changes necessary:

* Remove the ending period from the commit and the backticks from Server
* `:send-server-version` is a boolean value, so should end with a `?` for consistency
* The `testing` blocks should not contain code/comments in the string

**Comment by whysoserious** [comment]
> If you need this feature soon

I am already using patched version in my project

> here are some minor style changes necessary:

Done!

**Comment by weavejester** [comment]
Thanks! Could you also remove the backticks from the docstring? Ring doesn't (yet) use markdown in docstrings. Then I think it's good to merge.

**Comment by whysoserious** [comment]
> Could you also remove the backticks from the docstring?

Yeah, I missed that. Done.

**Pull request merged**
