### PR TITLE
add servlet support

### PR DESCRIPTION
**Pull request by jiacai2050**
ref: https://github.com/weavejester/compojure/issues/176

Add a new option to define servlet mapping

```
{:servlet-mapping {"/hello" (HelloServlet.)}}
```

### CODE REVIEW

**Comment by weavejester** [comment]
I think this would be better tested in a third-party library first.

**Comment by jiacai2050** [comment]
My company has used  [this adapter](https://github.com/killme2008/ring-jetty-hystrix-adapter) for almost two years, it use the same tricks: 
> If requests are not matched against servlet contexts, they are passed to the original handler.

**Comment by weavejester** [comment]
What's your reasoning for including this change in the Ring Jetty adapter itself if there is a third-party adapter already available? Do you believe it's a common enough use-case to include an option for?

Have you considered other solutions, such as converting a Java servlet into a Ring handler?

**Comment by jiacai2050** [comment]
Well, the adapter I referred is mainly to be used with hystrix, what if you have another servlet? Maybe write another adapter. And I have done this when using [druid's StatViewServlet](https://github.com/alibaba/druid/wiki/%E9%85%8D%E7%BD%AE_StatViewServlet%E9%85%8D%E7%BD%AE).

Converting a Java servlet into a Ring handler is indeed another solution, and I have done this several times when port a Java web application into a Ring-based application. I'm not sure if sevlet-mapping integration is common for others, I just want this feature now and then.
I hope Ring can support servlet out of box, no more no less.

**Comment by weavejester** [comment]
Could this be achieved instead with the existing `:configurator` option? Or a function that converts a servlet into a handler function?

**Comment by jiacai2050** [comment]
`configurator` option doesn't work for this. Since the adapter has already defined a handler, if set to another, then the original one will be lost.

I can't image what a general function converting servlet into a handler look like, after all it's servlet that does the real business, turning a request map to a HttpServletRequest is reasonable, but not otherwise.

**Comment by weavejester** [comment]
One possibility is that we provide an option to allow the adapter to include the [servlet keys](https://github.com/ring-clojure/ring/blob/master/ring-servlet/src/ring/util/servlet.clj#L55) that are already added when a handler is compiled into a servlet. Given this, converting a servlet into a handler becomes more straightforward.

I'm leery about adding a `:servlet-mapping` key to the adapter, as it provides a "back door" that exists outside the adapter specification. I'd prefer to have this tested in a third-party adapter first - one more general purpose than ring-jetty-hystrix-adapter - than add this as an option to Ring's official adapter without fully thinking through the consequences.

**Comment by jiacai2050** [comment]
OK, I get your point. 
I'm fine with the solution. I will contribute another adapter based on my code, and let the time tell.
Thanks for the hard work you have done with Ring.

**Comment by jiacai2050** [comment]
Done. https://github.com/jiacai2050/ring-jetty-servlet-adapter

**Pull request closed without merging**
