### PR TITLE
Fix multipart params reflection warning

### PR DESCRIPTION
**Pull request by RokLenarcic**
This PR addresses a reflection warning in multipart-params code.

### CODE REVIEW

**Comment by weavejester** [comment]
Thanks for the patch. Can you fix the indentation?

**Comment by RokLenarcic** [comment]
I think it's fixed now.

**Comment by weavejester** [comment]
The indentation is still incorrect. It needs to be the same level of indentation as before the patch was applied. So for example, `html5-encoding` needs to be level with `forced-encoding`

**Comment by RokLenarcic** [comment]
Hm, that's how my IDE formatted it. But why not just have it all in one line? Comes in at 113 characters.

**Comment by weavejester** [comment]
Ring follows the [Clojure Style Guide](https://github.com/bbatsov/clojure-style-guide), which suggests that lines be no more than 80 characters. This also fits with my own preference, as a line not much longer than that goes off screen in my editor.

**Pull request merged**
