### PR TITLE
make find-index-file prefer index.html

### PR DESCRIPTION
**Pull request by ryantm**
This addresses issue #48.  The tests don't actually test for it well since .listFiles is non deterministic and I didn't know how to mock an assets folder.  The code seems to work from my manual testing. Let me know what you think.

### CODE REVIEW

**Comment by weavejester** [comment]
This proposal makes sense, but could be implemented better. There's no need for a sort, just a condition that checks for `index.html` and `index.htm` specifically.

**Comment by ryantm** [comment]
@weavejester That sounds okay. I am probably not going to be working on this since I have moved away from doing Clojure work.

**Comment by weavejester** [comment]
No problem. I know this PR is very old.

**Comment by stig** [comment]
Would something _conceptually_ like this be acceptable?

```clojure
user> (let [foo ["index.js" "index.htm" "index.html" "index.frm"]]
        (or (some #{"index.html" "index.htm"} foo)
            (first foo)))
```

I don't see a way to address #48 without doing two passes over the list returned by the existing filter _in the worst case_, but this would at least be quick for the common(?) case of `index.html` or `index.htm` being present.

**Comment by weavejester** [comment]
Yes, that would be fine. The list of index files is so small it doesn't matter if we pass over it more than once. Alternatively, check for the existence of the HTML index files first, then go to the trouble of `.listFiles`.

**Comment by stig** [comment]
This issue has now been addressed via #239, so I think it can be closed.

**Pull request closed without merging**
