### PR TITLE
added :welcome-page-conf usage: {:port 8080 :welcome-page-conf {:reso…

### PR DESCRIPTION
**Pull request by ertugrulcetin**
Sets jetty welcome/default page.
Ex: index.html
Could be useful for single page applications.

usage: {:port 8080
             :welcome-page-conf {:resource-base "resources" 
                                               :welcome-page "index.html"}}

### CODE REVIEW

**Comment by weavejester** [comment]
Thanks for the patch, but I don't want to add functionality to the adapter that could instead be written as a handler or with middleware.

**Comment by ertugrulcetin** [comment]
Could you provide a simple snippet(middleware) for achieving this functionality?

**Comment by weavejester** [comment]
Sure. I actually have some middleware already that does this [in Duct](https://github.com/weavejester/duct/blob/master/duct/src/duct/middleware/route_aliases.clj)

So using the "route-aliases" middleware, you could write:

```clojure
(-> handler
    (wrap-resources)
    (wrap-route-aliases {"/" "index.html"}))
```

You could also write it as a handler using a routing library like [Compojure](https://github.com/weavejester/compojure):

```clojure
(def handler
  (routes
   (GET "/" [] (io/resource "index.html"))
   (route/resources "/")
   (route/not-found "Not Found"))
```

**Comment by ertugrulcetin** [comment]
Thank you so much!

**Pull request closed without merging**
