### PR TITLE
Add :same-site key to response cookie attributes

### PR DESCRIPTION
**Pull request by jakemcc**
SameSite attribute allows servers to assert that a cookie out not to
be sent along with cross-site requests. Proposed in
https://tools.ietf.org/html/draft-west-first-party-cookies-07.

With help from Daniel Solano Gómez @sattvik

### CODE REVIEW

**Comment by weavejester** [comment]
Thanks for the patch. There are a couple of minor things that need to be fixed before it can be merged:

1. The commit message needs to adhere to [the seven rules](http://chris.beams.io/posts/git-commit/#seven-rules)
2. "Strict" and "Lax" should be keywords, `:strict` and `:lax`.

**Comment by jakemcc** [comment]
@weavejester Updated the commit message and switched so `:strict` and `:lax` are the supported values.

If something else needs to change with the commit message I'd ask that you point out specifics so I don't just guess. I removed the obvious mistake of the period at the end of the first line and removed the credit to @sattvik in the commit message body (we happened to be pairing when I decided I wanted to add this feature).

**Comment by weavejester** [comment]
> Updated the commit message and switched so :strict and :lax are the supported values.

Thanks!

> If something else needs to change with the commit message I'd ask that you point out specifics so I don't just guess.

I usually do, but I thought I'd try to save time and point you to the link directly. I'm sure you can understand that I get a lot of pull requests, and many of them have formatting issues of some kind.

Can you change the commit message to:

    Add :same-site key to response cookie attributes

    The "SameSite" attribute allows servers to assert that a cookie should
    not be sent along with cross-site requests. Proposed in:
    https://tools.ietf.org/html/draft-west-first-party-cookies-07.

I've reworded the commit subject to be in the imperative mood (so like a command, rather than a description), and I've corrected "out not to" to "should not".

**Comment by jakemcc** [comment]
@weavejester I completely understand trying to save time. Even with the significantly smaller tools and libraries I maintain every PR I review and then accept or reject carries a significant cost on my own time. I can imagine the timesink it is for you.

Thanks for the assistance. Hope my earlier response didn't come off snarky. It definitely wasn't intended that way.

Commit message updated.

**Pull request merged**
