### PR TITLE
Prevent temp filename leak in multipart uploads

### PR DESCRIPTION
**Pull request by fofanov**
Currently the temporary file store can be used to manage multipart files, where
the deleteOnExit hook is applied to each new file. Whilst these temp files are
deleted by the temp-file-store periodically, all filenames remain in a
LinkedHashSet in DeleteOnExitHook with the intention that it cleans up any
remaining files on shutdown. However, for a long running service this
accumulation of deleted filenames acts as a memory leak leading to heap OOM
errors. The proposed solution is to use the file-set the store is already tracking
and attach our own shutdown hook that cleans up any remaining files.

### CODE REVIEW

**Comment by fofanov** [comment]
This appears to be failing CI due to an unrelated Jetty test.

**Comment by weavejester** [comment]
Jetty 9 seems to be very slow about cleaning up its threads, leading to issues with the tests. I thought I fixed it with a 10 second timeout, but it seems even that's too short!

Thanks for the patch. Could you shorten the commit message a little - it doesn't need to be as long as the related PR. Something like:

```
Prevent temp filename leak in multipart uploads

The deleteOnExit hook adds files to a LinkedHashSet, which continues to
grow even when those files are periodically deleted. This causes a slow
memory leak, which can be solved by replacing deleteOnExit with a custom
shutdown hook.
```

**Comment by fofanov** [comment]
Thanks, I've shortened the commit message as suggested.

**Comment by weavejester** [comment]
Excellent. Thanks!

**Pull request merged**
