### PR TITLE
Allow namespace style keywords as param names

### PR DESCRIPTION
**Pull request by jxa**
Currently params with names such as "namespace/param-name" are skipped because "/" is not allowed by keyword-syntax? function.

### CODE REVIEW

**Comment by iku000888** [comment]
@weavejester this enhancement would be really nice. Is the conflict the only thing blocking this to be merged?

**Comment by iku000888** [comment]
ping? @weavejester

**Comment by weavejester** [comment]
I'll take a look and try and get it up to standard to be merged.

**Comment by weavejester** [comment]
Merged manually.

**Comment by iku000888** [comment]
Thanks so much for your time! I think a lot of people will like this addition

**Pull request closed without merging**
