### PR TITLE
Add type hint for proxy-handler

### PR DESCRIPTION
**Pull request by matejvasek**
Fixes possible issues with GraalVM native-image.

### CODE REVIEW

**Comment by weavejester** [comment]
Thanks for the patch. I think it might be better to put the type hint on the argument list, and you're also going to need to change the commit message to adhere to the contributing guidelines before it can be merged.

**Comment by matejvasek** [comment]
@weavejester done.

**Comment by matejvasek** [comment]
I thing this fixes #396.

**Comment by weavejester** [comment]
Thanks. You have a small typo - "wiht" instead of "with" - and "graalvm" is generally capitalised as "GraalVM". The "Signed-off-by" field is also unncessary in this case, as it's the same as the commit author, and Ring doesn't use a DCO.

**Comment by matejvasek** [comment]
@weavejester this is weird, I just changed commit message and a test return non-zero code, but there are no failed tests.

**Comment by weavejester** [comment]
> @weavejester this is weird, I just changed commit message and a test return non-zero code, but there are no failed tests.

It's just an issue with the CI server not being able to download a dependency from the maven server. I've restarted the CI build.

**Pull request merged**
