### PR TITLE
Preload Cipher class for cookie-store performance

### LINKED ISSUE #264: First usage of cookie-store is slow
It appears that it's caused by the lazy-loading encryption stuff (4-5s!). A fix that appeared to work was this:

```clojure
(import '[javax.crypto Cipher]) 
(Cipher/getInstance "AES/CBC/PKCS5Padding")
```

Could we possibly integrate a preload into the namespace?

### PR DESCRIPTION
**Pull request by martinskou**
Preload Cipher class for cookie-store performance

Fixes #264.

### CODE REVIEW

**Comment by weavejester** [comment]
For reference, this continues on from #265.

**Comment by weavejester** [comment]
Thanks for the new PR, but you've put the same line twice in your commit message.

To change it, use:

    git commit --amend

Then once you've deleted one of the duplicate lines:

    git push -f

**Comment by martinskou** [comment]
Yes, thanks, I should spend some more time with Git :-)

Hope the issues is fixed now.


--
Martin Skou Drewes | Udviklingschef | Webbureauet Infoserv ApS
T: 70107600 | D: 87110302 | http://infoserv.dk | http://aviva.dk

**Comment by weavejester** [comment]
I'm afraid the commit message still has a duplicated line in it.

**Comment by martinskou** [comment]
Sorry, has now been fixed.

**Pull request merged**
